In [52]:
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta
import financedatabase as fd

In [125]:
from financetoolkit import Toolkit

companies = Toolkit(
    tickers=['GOOGL','MSFT'],
    api_key="38NHcGNjsNLRH6DIeedCqQXFK0Rv8FqF",
)

In [126]:
# a Historical example
historical_data = companies.get_historical_data()

Obtaining historical data: 100%|██████████| 3/3 [00:00<00:00,  9.35it/s]

In [127]:
bs = companies.get_balance_sheet_statement()

Obtaining balance data: 100%|██████████| 2/2 [00:00<00:00,  9.37it/s]

In [129]:
bs.loc['GOOGL']

date,2019,2020,2021,2022,2023,2024
Cash and Cash Equivalents,18498000000.0,26465000000.0,20945000000.0,21879000000.0,24048000000.0,NaN
Short Term Investments,101177000000.0,110229000000.0,118704000000.0,91883000000.0,86868000000.0,NaN
Cash and Short Term Investments,119675000000.0,136694000000.0,139649000000.0,113762000000.0,110916000000.0,NaN
Accounts Receivable,27492000000.0,31384000000.0,39304000000.0,40258000000.0,47964000000.0,NaN
Inventory,999000000.0,728000000.0,1170000000.0,2670000000.0,0.0,NaN
Other Current Assets,4412000000.0,5490000000.0,8020000000.0,8105000000.0,12650000000.0,NaN
Total Current Assets,152578000000.0,174296000000.0,188143000000.0,164795000000.0,171530000000.0,NaN
"Property, Plant and Equipment",84587000000.0,96960000000.0,110558000000.0,127049000000.0,148436000000.0,NaN
Goodwill,20624000000.0,21175000000.0,22956000000.0,28960000000.0,29198000000.0,NaN
Intangible Assets,1979000000.0,1445000000.0,1417000000.0,2084000000.0,0.0,NaN
Long Term Investments,13078000000.0,20703000000.0,29549000000.0,30492000000.0,31008000000.0,NaN
Tax Assets,721000000.0,1084000000.0,1284000000.0,5261000000.0,12169000000.0,NaN
Other Fixed Assets,2342000000.0,3953000000.0,5361000000.0,6623000000.0,10051000000.0,NaN
Fixed Assets,123331000000.0,145320000000.0,171125000000.0,200469000000.0,230862000000.0,NaN
Other Assets,0.0,0.0,0.0,0.0,0.0,NaN
Total Assets,275909000000.0,319616000000.0,359268000000.0,365264000000.0,402392000000.0,NaN
Accounts Payable,5561000000.0,5589000000.0,6037000000.0,5128000000.0,7493000000.0,NaN
Short Term Debt,1199000000.0,1694000000.0,2189000000.0,2477000000.0,2791000000.0,NaN
Tax Payables,274000000.0,1485000000.0,808000000.0,9258000000.0,2748000000.0,NaN
Deferred Revenue,1908000000.0,2543000000.0,3288000000.0,3908000000.0,4137000000.0,NaN
Other Current Liabilities,36279000000.0,45523000000.0,51932000000.0,48529000000.0,64645000000.0,NaN
Total Current Liabilities,45221000000.0,56834000000.0,64254000000.0,69300000000.0,81814000000.0,NaN
Long Term Debt,24982000000.0,37324000000.0,39568000000.0,39703000000.0,39556000000.0,NaN
Deferred Revenue Non Current,358000000.0,481000000.0,535000000.0,599000000.0,911000000.0,NaN
Deferred Tax Liabilities,1701000000.0,3561000000.0,5257000000.0,514000000.0,485000000.0,NaN
Other Non Current Liabilities,2205000000.0,-1128000000.0,-1981000000.0,-996000000.0,-3753000000.0,NaN
Total Non Current Liabilities,29246000000.0,40238000000.0,43379000000.0,39820000000.0,37199000000.0,NaN
Other Liabilities,0.0,0.0,0.0,0.0,0.0,NaN
Capital Lease Obligations,11413000000.0,13940000000.0,15551000000.0,14978000000.0,16634000000.0,NaN
Total Liabilities,74467000000.0,97072000000.0,107633000000.0,109120000000.0,119013000000.0,NaN
Preferred Stock,0.0,0.0,0.0,0.0,0.0,NaN
Common Stock,50552000000.0,58510000000.0,61774000000.0,68184000000.0,76534000000.0,NaN
Retained Earnings,152122000000.0,163401000000.0,191484000000.0,195563000000.0,211247000000.0,NaN
Accumulated Other Comprehensive Income,-1232000000.0,633000000.0,-1623000000.0,-7603000000.0,-4402000000.0,NaN
Other Total Shareholder Equity,0.0,0.0,0.0,0.0,0.0,NaN
Total Shareholder Equity,201442000000.0,222544000000.0,251635000000.0,256144000000.0,283379000000.0,NaN
Total Equity,201442000000.0,222544000000.0,251635000000.0,256144000000.0,283379000000.0,NaN
Total Liabilities and Shareholder Equity,275909000000.0,319616000000.0,359268000000.0,365264000000.0,402392000000.0,NaN
Minority Interest,0.0,0.0,0.0,0.0,0.0,NaN
Total Liabilities and Equity,275909000000.0,319616000000.0,359268000000.0,365264000000.0,402392000000.0,NaN
Total Investments,114255000000.0,130932000000.0,148253000000.0,122375000000.0,117876000000.0,NaN
Total Debt,14768000000.0,25078000000.0,26206000000.0,29679000000.0,28504000000.0,NaN
Net Debt,-3730000000.0,-1387000000.0,5261000000.0,7800000000.0,4456000000.0,NaN

In [101]:
metrics_list = pd.read_parquet('metrics_list.parquet', engine='pyarrow')

In [104]:
metrics_list.columns = ['metrics']

In [105]:
metrics_list

                                  metrics
0          Cash and Cash Equivalents (BS)
1             Short Term Investments (BS)
2    Cash and Short Term Investments (BS)
3                Accounts Receivable (BS)
4                          Inventory (BS)
..                                    ...
234                 Maximum Drawdown (RI)
235                      Ulcer Index (RI)
236                            GARCH (RI)
237                         Skewness (RI)
238                         Kurtosis (RI)

[239 rows x 1 columns]

In [96]:
stock.history(interval='10s', period='1d')

$AAPL: possibly delisted; no price data found  (period=1d) (Yahoo error = "Invalid input - interval=10s is not supported. Valid intervals: [1m, 2m, 5m, 15m, 30m, 60m, 90m, 1h, 1d, 5d, 1wk, 1mo, 3mo]")

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [44]:

def get_sp500_components():
    """
    Get current S&P 500 components using Wikipedia
    """
    table = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
    df = table[0]
    return df[['Symbol', 'GICS Sector', 'GICS Sub-Industry']]

In [45]:
sp500 = get_sp500_components()

In [46]:
sp500.groupby('GICS Sector').agg({'Symbol':'count', 'GICS Sub-Industry': 'nunique'}).sort_values('Symbol', ascending= False)

                        Symbol  GICS Sub-Industry
GICS Sector
Industrials                 78                 20
Financials                  72                 13
Information Technology      69                 12
Health Care                 62                 10
Consumer Discretionary      50                 18
Consumer Staples            38                 12
Real Estate                 31                 13
Utilities                   31                  5
Materials                   28                 10
Communication Services      22                  9
Energy                      22                  5

In [29]:

def fetch_daily_data(symbol, start_date, end_date):
    """
    Fetch daily data using yfinance
    """
    stock = yf.Ticker(symbol)
    df = stock.history(start=start_date, end=end_date)
    return df

In [30]:
fetch_daily_data('AAPL', '2024-01-01', '2024-12-02')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-01-02 00:00:00-05:00,186.237603,187.521323,182.993502,184.734970,82488700,0.0,0.0
2024-01-03 00:00:00-05:00,183.321893,184.973804,182.535736,183.351746,58414500,0.0,0.0
2024-01-04 00:00:00-05:00,181.261983,182.197403,179.998185,181.023163,71983600,0.0,0.0
2024-01-05 00:00:00-05:00,181.102771,181.869006,179.291637,180.296707,62303300,0.0,0.0
2024-01-08 00:00:00-05:00,181.202281,184.695178,180.615161,184.655365,59144500,0.0,0.0
...,...,...,...,...,...,...,...
2024-11-22 00:00:00-05:00,228.059998,230.720001,228.059998,229.869995,38168300,0.0,0.0
2024-11-25 00:00:00-05:00,231.460007,233.250000,229.740005,232.869995,90152800,0.0,0.0
2024-11-26 00:00:00-05:00,233.330002,235.570007,233.330002,235.059998,45986200,0.0,0.0
2024-11-27 00:00:00-05:00,234.470001,235.690002,233.809998,234.929993,33498400,0.0,0.0
2024-11-29 00:00:00-05:00,234.809998,237.809998,233.970001,237.330002,28481400,0.0,0.0

In [ ]:

def fetch_intraday_data(symbol, interval='1m', start_date= '2024-12-02 07:00:00'):
    """
    Fetch intraday data using yfinance
    Note: Free tier limitations apply
    """
    stock = yf.Ticker(symbol)
    # yfinance provides up to 7 days of 1-minute data
    df = stock.history(interval=interval, start=start_date)
    return df

In [33]:
stock = yf.Ticker('AAPL')
# yfinance provides up to 7 days of 1-minute data

In [ ]:
from datetime import date

In [38]:
sd = datetime(2024,12,2,7,0,0)

In [42]:
ed = datetime.now()

In [41]:
stock.history(interval='1m', start=sd, end=ed)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2024-12-02 09:30:00-05:00,237.270004,238.770004,237.160004,238.700897,2562715,0.0,0.0
2024-12-02 09:31:00-05:00,238.690002,239.059906,238.399994,239.000000,418941,0.0,0.0
2024-12-02 09:32:00-05:00,238.960007,239.350006,238.910004,238.934601,213308,0.0,0.0
2024-12-02 09:33:00-05:00,238.929993,239.199997,238.729996,239.110001,192847,0.0,0.0
2024-12-02 09:34:00-05:00,239.080093,239.350006,238.929993,239.296295,200970,0.0,0.0
...,...,...,...,...,...,...,...
2024-12-02 11:51:00-05:00,239.958694,239.990097,239.925003,239.970001,36202,0.0,0.0
2024-12-02 11:52:00-05:00,239.960007,240.000000,239.960007,239.994507,58478,0.0,0.0
2024-12-02 11:53:00-05:00,239.990005,240.000000,239.789993,239.869995,68897,0.0,0.0
2024-12-02 11:54:00-05:00,239.860001,239.899994,239.850006,239.850098,25780,0.0,0.0
2024-12-02 11:55:00-05:00,239.835007,239.835007,239.835007,239.835007,0,0.0,0.0

In [7]:

def calculate_industry_stats(daily_data_dict, sp500_components):
    """
    Calculate industry-specific statistics
    """
    industry_stats = {}
    
    for industry in sp500_components['GICS Sub-Industry'].unique():
        industry_symbols = sp500_components[sp500_components['GICS Sub-Industry'] == industry]['Symbol'].tolist()
        industry_data = pd.concat([daily_data_dict[sym] for sym in industry_symbols if sym in daily_data_dict])
        
        if not industry_data.empty:
            # Calculate industry-specific metrics
            industry_stats[industry] = {
                'daily_returns': industry_data['Close'].pct_change().mean(),
                'volatility': industry_data['Close'].pct_change().std(),
                'volume': industry_data['Volume'].mean(),
                'symbols_count': len(industry_symbols)
            }
    
    return pd.DataFrame(industry_stats).T

In [8]:

def main():
    # Get S&P 500 components
    sp500_components = get_sp500_components()
    
    # Set date range
    end_date = datetime.now()
    start_date = end_date - timedelta(days=365)  # Last year of daily data
    
    # Fetch daily data for all S&P 500 components
    daily_data = {}
    for symbol in sp500_components['Symbol']:
        try:
            daily_data[symbol] = fetch_daily_data(symbol, start_date, end_date)
            print(f"Fetched daily data for {symbol}")
        except Exception as e:
            print(f"Error fetching {symbol}: {e}")
    
    # Calculate industry statistics
    industry_stats = calculate_industry_stats(daily_data, sp500_components)
    
    # Example: Fetch intraday data for a specific symbol
    symbol = "SPY"  # S&P 500 ETF
    intraday_data = fetch_intraday_data(symbol)
    
    return daily_data, intraday_data, industry_stats

In [9]:
daily_data, intraday_data, industry_stats = main()

Fetched daily data for MMM
Fetched daily data for AOS
Fetched daily data for ABT
Fetched daily data for ABBV
Fetched daily data for ACN
Fetched daily data for ADBE
Fetched daily data for AMD
Fetched daily data for AES
Fetched daily data for AFL
Fetched daily data for A
Fetched daily data for APD
Fetched daily data for ABNB
Fetched daily data for AKAM
Fetched daily data for ALB
Fetched daily data for ARE
Fetched daily data for ALGN
Fetched daily data for ALLE
Fetched daily data for LNT
Fetched daily data for ALL
Fetched daily data for GOOGL
Fetched daily data for GOOG
Fetched daily data for MO
Fetched daily data for AMZN
Fetched daily data for AMCR
Fetched daily data for AMTM
Fetched daily data for AEE
Fetched daily data for AEP
Fetched daily data for AXP
Fetched daily data for AIG
Fetched daily data for AMT
Fetched daily data for AWK
Fetched daily data for AMP
Fetched daily data for AME
Fetched daily data for AMGN
Fetched daily data for APH
Fetched daily data for ADI
Fetched daily data for ANSS
Fetched daily data for AON
Fetched daily data for APA
Fetched daily data for AAPL
Fetched daily data for AMAT
Fetched daily data for APTV
Fetched daily data for ACGL
Fetched daily data for ADM
Fetched daily data for ANET
Fetched daily data for AJG
Fetched daily data for AIZ
Fetched daily data for T
Fetched daily data for ATO
Fetched daily data for ADSK
Fetched daily data for ADP
Fetched daily data for AZO
Fetched daily data for AVB
Fetched daily data for AVY
Fetched daily data for AXON
Fetched daily data for BKR
Fetched daily data for BALL
Fetched daily data for BAC
Fetched daily data for BAX
Fetched daily data for BDX

$BRK.B: possibly delisted; no timezone found

Fetched daily data for BRK.B
Fetched daily data for BBY
Fetched daily data for TECH
Fetched daily data for BIIB
Fetched daily data for BLK
Fetched daily data for BX
Fetched daily data for BK
Fetched daily data for BA
Fetched daily data for BKNG
Fetched daily data for BWA
Fetched daily data for BSX
Fetched daily data for BMY
Fetched daily data for AVGO
Fetched daily data for BR

$BF.B: possibly delisted; no price data found  (1d 2023-12-03 15:41:11.598004 -> 2024-12-02 15:41:11.598004)

Fetched daily data for BRO
Fetched daily data for BF.B
Fetched daily data for BLDR
Fetched daily data for BG
Fetched daily data for BXP
Fetched daily data for CHRW
Fetched daily data for CDNS
Fetched daily data for CZR
Fetched daily data for CPT
Fetched daily data for CPB
Fetched daily data for COF
Fetched daily data for CAH
Fetched daily data for KMX
Fetched daily data for CCL
Fetched daily data for CARR
Fetched daily data for CTLT
Fetched daily data for CAT
Fetched daily data for CBOE
Fetched daily data for CBRE
Fetched daily data for CDW
Fetched daily data for CE
Fetched daily data for COR
Fetched daily data for CNC
Fetched daily data for CNP
Fetched daily data for CF
Fetched daily data for CRL
Fetched daily data for SCHW
Fetched daily data for CHTR
Fetched daily data for CVX
Fetched daily data for CMG
Fetched daily data for CB
Fetched daily data for CHD
Fetched daily data for CI
Fetched daily data for CINF
Fetched daily data for CTAS
Fetched daily data for CSCO
Fetched daily data for C
Fetched daily data for CFG
Fetched daily data for CLX
Fetched daily data for CME
Fetched daily data for CMS
Fetched daily data for KO
Fetched daily data for CTSH
Fetched daily data for CL
Fetched daily data for CMCSA
Fetched daily data for CAG
Fetched daily data for COP
Fetched daily data for ED
Fetched daily data for STZ
Fetched daily data for CEG
Fetched daily data for COO
Fetched daily data for CPRT
Fetched daily data for GLW
Fetched daily data for CPAY
Fetched daily data for CTVA
Fetched daily data for CSGP
Fetched daily data for COST
Fetched daily data for CTRA
Fetched daily data for CRWD
Fetched daily data for CCI
Fetched daily data for CSX
Fetched daily data for CMI
Fetched daily data for CVS
Fetched daily data for DHR
Fetched daily data for DRI
Fetched daily data for DVA
Fetched daily data for DAY
Fetched daily data for DECK
Fetched daily data for DE
Fetched daily data for DELL
Fetched daily data for DAL
Fetched daily data for DVN
Fetched daily data for DXCM
Fetched daily data for FANG
Fetched daily data for DLR
Fetched daily data for DFS
Fetched daily data for DG
Fetched daily data for DLTR
Fetched daily data for D
Fetched daily data for DPZ
Fetched daily data for DOV
Fetched daily data for DOW
Fetched daily data for DHI
Fetched daily data for DTE
Fetched daily data for DUK
Fetched daily data for DD
Fetched daily data for EMN
Fetched daily data for ETN
Fetched daily data for EBAY
Fetched daily data for ECL
Fetched daily data for EIX
Fetched daily data for EW
Fetched daily data for EA
Fetched daily data for ELV
Fetched daily data for EMR
Fetched daily data for ENPH
Fetched daily data for ETR
Fetched daily data for EOG
Fetched daily data for EPAM
Fetched daily data for EQT
Fetched daily data for EFX
Fetched daily data for EQIX
Fetched daily data for EQR
Fetched daily data for ERIE
Fetched daily data for ESS
Fetched daily data for EL
Fetched daily data for EG
Fetched daily data for EVRG
Fetched daily data for ES
Fetched daily data for EXC
Fetched daily data for EXPE
Fetched daily data for EXPD
Fetched daily data for EXR
Fetched daily data for XOM
Fetched daily data for FFIV
Fetched daily data for FDS
Fetched daily data for FICO
Fetched daily data for FAST
Fetched daily data for FRT
Fetched daily data for FDX
Fetched daily data for FIS
Fetched daily data for FITB
Fetched daily data for FSLR
Fetched daily data for FE
Fetched daily data for FI
Fetched daily data for FMC
Fetched daily data for F
Fetched daily data for FTNT
Fetched daily data for FTV
Fetched daily data for FOXA
Fetched daily data for FOX
Fetched daily data for BEN
Fetched daily data for FCX
Fetched daily data for GRMN
Fetched daily data for IT
Fetched daily data for GE
Fetched daily data for GEHC
Fetched daily data for GEV
Fetched daily data for GEN
Fetched daily data for GNRC
Fetched daily data for GD
Fetched daily data for GIS
Fetched daily data for GM
Fetched daily data for GPC
Fetched daily data for GILD
Fetched daily data for GPN
Fetched daily data for GL
Fetched daily data for GDDY
Fetched daily data for GS
Fetched daily data for HAL
Fetched daily data for HIG
Fetched daily data for HAS
Fetched daily data for HCA
Fetched daily data for DOC
Fetched daily data for HSIC
Fetched daily data for HSY
Fetched daily data for HES
Fetched daily data for HPE
Fetched daily data for HLT
Fetched daily data for HOLX
Fetched daily data for HD
Fetched daily data for HON
Fetched daily data for HRL
Fetched daily data for HST
Fetched daily data for HWM
Fetched daily data for HPQ
Fetched daily data for HUBB
Fetched daily data for HUM
Fetched daily data for HBAN
Fetched daily data for HII
Fetched daily data for IBM
Fetched daily data for IEX
Fetched daily data for IDXX
Fetched daily data for ITW
Fetched daily data for INCY
Fetched daily data for IR
Fetched daily data for PODD
Fetched daily data for INTC
Fetched daily data for ICE
Fetched daily data for IFF
Fetched daily data for IP
Fetched daily data for IPG
Fetched daily data for INTU
Fetched daily data for ISRG
Fetched daily data for IVZ
Fetched daily data for INVH
Fetched daily data for IQV
Fetched daily data for IRM
Fetched daily data for JBHT
Fetched daily data for JBL
Fetched daily data for JKHY
Fetched daily data for J
Fetched daily data for JNJ
Fetched daily data for JCI
Fetched daily data for JPM
Fetched daily data for JNPR
Fetched daily data for K
Fetched daily data for KVUE
Fetched daily data for KDP
Fetched daily data for KEY
Fetched daily data for KEYS
Fetched daily data for KMB
Fetched daily data for KIM
Fetched daily data for KMI
Fetched daily data for KKR
Fetched daily data for KLAC
Fetched daily data for KHC
Fetched daily data for KR
Fetched daily data for LHX
Fetched daily data for LH
Fetched daily data for LRCX
Fetched daily data for LW
Fetched daily data for LVS
Fetched daily data for LDOS
Fetched daily data for LEN
Fetched daily data for LLY
Fetched daily data for LIN
Fetched daily data for LYV
Fetched daily data for LKQ
Fetched daily data for LMT
Fetched daily data for L
Fetched daily data for LOW
Fetched daily data for LULU
Fetched daily data for LYB
Fetched daily data for MTB
Fetched daily data for MPC
Fetched daily data for MKTX
Fetched daily data for MAR
Fetched daily data for MMC
Fetched daily data for MLM
Fetched daily data for MAS
Fetched daily data for MA
Fetched daily data for MTCH
Fetched daily data for MKC
Fetched daily data for MCD
Fetched daily data for MCK
Fetched daily data for MDT
Fetched daily data for MRK
Fetched daily data for META
Fetched daily data for MET
Fetched daily data for MTD
Fetched daily data for MGM
Fetched daily data for MCHP
Fetched daily data for MU
Fetched daily data for MSFT
Fetched daily data for MAA
Fetched daily data for MRNA
Fetched daily data for MHK
Fetched daily data for MOH
Fetched daily data for TAP
Fetched daily data for MDLZ
Fetched daily data for MPWR
Fetched daily data for MNST
Fetched daily data for MCO
Fetched daily data for MS
Fetched daily data for MOS
Fetched daily data for MSI
Fetched daily data for MSCI
Fetched daily data for NDAQ
Fetched daily data for NTAP
Fetched daily data for NFLX
Fetched daily data for NEM
Fetched daily data for NWSA
Fetched daily data for NWS
Fetched daily data for NEE
Fetched daily data for NKE
Fetched daily data for NI
Fetched daily data for NDSN
Fetched daily data for NSC
Fetched daily data for NTRS
Fetched daily data for NOC
Fetched daily data for NCLH
Fetched daily data for NRG
Fetched daily data for NUE
Fetched daily data for NVDA
Fetched daily data for NVR
Fetched daily data for NXPI
Fetched daily data for ORLY
Fetched daily data for OXY
Fetched daily data for ODFL
Fetched daily data for OMC
Fetched daily data for ON
Fetched daily data for OKE
Fetched daily data for ORCL
Fetched daily data for OTIS
Fetched daily data for PCAR
Fetched daily data for PKG
Fetched daily data for PLTR
Fetched daily data for PANW
Fetched daily data for PARA
Fetched daily data for PH
Fetched daily data for PAYX
Fetched daily data for PAYC
Fetched daily data for PYPL
Fetched daily data for PNR
Fetched daily data for PEP
Fetched daily data for PFE
Fetched daily data for PCG
Fetched daily data for PM
Fetched daily data for PSX
Fetched daily data for PNW
Fetched daily data for PNC
Fetched daily data for POOL
Fetched daily data for PPG
Fetched daily data for PPL
Fetched daily data for PFG
Fetched daily data for PG
Fetched daily data for PGR
Fetched daily data for PLD
Fetched daily data for PRU
Fetched daily data for PEG
Fetched daily data for PTC
Fetched daily data for PSA
Fetched daily data for PHM
Fetched daily data for QRVO
Fetched daily data for PWR
Fetched daily data for QCOM
Fetched daily data for DGX
Fetched daily data for RL
Fetched daily data for RJF
Fetched daily data for RTX
Fetched daily data for O
Fetched daily data for REG
Fetched daily data for REGN
Fetched daily data for RF
Fetched daily data for RSG
Fetched daily data for RMD
Fetched daily data for RVTY
Fetched daily data for ROK
Fetched daily data for ROL
Fetched daily data for ROP
Fetched daily data for ROST
Fetched daily data for RCL
Fetched daily data for SPGI
Fetched daily data for CRM
Fetched daily data for SBAC
Fetched daily data for SLB
Fetched daily data for STX
Fetched daily data for SRE
Fetched daily data for NOW
Fetched daily data for SHW
Fetched daily data for SPG
Fetched daily data for SWKS
Fetched daily data for SJM
Fetched daily data for SW
Fetched daily data for SNA
Fetched daily data for SOLV
Fetched daily data for SO
Fetched daily data for LUV
Fetched daily data for SWK
Fetched daily data for SBUX
Fetched daily data for STT
Fetched daily data for STLD
Fetched daily data for STE
Fetched daily data for SYK
Fetched daily data for SMCI
Fetched daily data for SYF
Fetched daily data for SNPS
Fetched daily data for SYY
Fetched daily data for TMUS
Fetched daily data for TROW
Fetched daily data for TTWO
Fetched daily data for TPR
Fetched daily data for TRGP
Fetched daily data for TGT
Fetched daily data for TEL
Fetched daily data for TDY
Fetched daily data for TFX
Fetched daily data for TER
Fetched daily data for TSLA
Fetched daily data for TXN
Fetched daily data for TPL
Fetched daily data for TXT
Fetched daily data for TMO
Fetched daily data for TJX
Fetched daily data for TSCO
Fetched daily data for TT
Fetched daily data for TDG
Fetched daily data for TRV
Fetched daily data for TRMB
Fetched daily data for TFC
Fetched daily data for TYL
Fetched daily data for TSN
Fetched daily data for USB
Fetched daily data for UBER
Fetched daily data for UDR
Fetched daily data for ULTA
Fetched daily data for UNP
Fetched daily data for UAL
Fetched daily data for UPS
Fetched daily data for URI
Fetched daily data for UNH
Fetched daily data for UHS
Fetched daily data for VLO
Fetched daily data for VTR
Fetched daily data for VLTO
Fetched daily data for VRSN
Fetched daily data for VRSK
Fetched daily data for VZ
Fetched daily data for VRTX
Fetched daily data for VTRS
Fetched daily data for VICI
Fetched daily data for V
Fetched daily data for VST
Fetched daily data for VMC
Fetched daily data for WRB
Fetched daily data for GWW
Fetched daily data for WAB
Fetched daily data for WBA
Fetched daily data for WMT
Fetched daily data for DIS
Fetched daily data for WBD
Fetched daily data for WM
Fetched daily data for WAT
Fetched daily data for WEC
Fetched daily data for WFC
Fetched daily data for WELL
Fetched daily data for WST
Fetched daily data for WDC
Fetched daily data for WY
Fetched daily data for WMB
Fetched daily data for WTW
Fetched daily data for WYNN
Fetched daily data for XEL
Fetched daily data for XYL
Fetched daily data for YUM
Fetched daily data for ZBRA
Fetched daily data for ZBH
Fetched daily data for ZTS

/var/folders/4x/48wx0c5156g28f5nn0ljxn4w0000gn/T/ipykernel_34125/4250306770.py:9: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  industry_data = pd.concat([daily_data_dict[sym] for sym in industry_symbols if sym in daily_data_dict])
SPY: Period '7d' is invalid, must be one of ['1d', '5d', '1mo', '3mo', '6mo', '1y', '2y', '5y', '10y', 'ytd', 'max']